extends Node
## 로컬라이제이션. 오토로드 이름: Loc
## 번역을 코드에 내장해 임포트 파이프라인 없이도 한국어가 항상 동작한다.
## 기본 언어는 한국어이며, 일시정지 메뉴에서 영어로 전환할 수 있다.

func _ready() -> void:
	var ko := Translation.new()
	ko.locale = "ko"
	var en := Translation.new()
	en.locale = "en"
	for key in KO:
		ko.add_message(key, KO[key])
	for key in EN:
		en.add_message(key, EN[key])
	TranslationServer.add_translation(ko)
	TranslationServer.add_translation(en)
	TranslationServer.set_locale("ko")

# ══════════════════════════════════════════════════════════ 한국어
const KO := {
	# ── 바이옴 ──
	"BIOME_OCEAN": "대양", "BIOME_MEADOWS": "초원", "BIOME_BLACKFOREST": "검은 숲",
	"BIOME_SWAMP": "늪지", "BIOME_MOUNTAIN": "설산", "BIOME_PLAINS": "평원",
	"BIOME_MISTLANDS": "안개의 땅", "BIOME_ASHLANDS": "잿불의 땅",

	# ── 데미지 ──
	"DMG_BLUNT": "타격", "DMG_SLASH": "베기", "DMG_PIERCE": "관통", "DMG_CHOP": "벌목",
	"DMG_PICKAXE": "채광", "DMG_FIRE": "화염", "DMG_FROST": "냉기", "DMG_POISON": "독",
	"DMG_LIGHTNING": "번개", "DMG_SPIRIT": "영혼",

	# ── 스킬 ──
	"SKILL_RUN": "달리기", "SKILL_JUMP": "도약", "SKILL_SWIM": "수영", "SKILL_SNEAK": "은신",
	"SKILL_BLOCK": "방어", "SKILL_AXES": "도끼", "SKILL_CLUBS": "둔기", "SKILL_SWORDS": "검",
	"SKILL_SPEARS": "창", "SKILL_KNIVES": "단검", "SKILL_BOWS": "활", "SKILL_UNARMED": "맨손",
	"SKILL_PICKAXES": "곡괭이", "SKILL_WOODCUTTING": "벌목",

	# ── 재료 ──
	"ITEM_WOOD": "나무", "ITEM_CORE_WOOD": "심재", "ITEM_FINE_WOOD": "고급 목재",
	"ITEM_ANCIENT_BARK": "고대 나무껍질", "ITEM_YGGDRASIL_WOOD": "위그드라실 목재",
	"ITEM_STONE": "돌", "ITEM_FLINT": "부싯돌", "ITEM_RESIN": "송진",
	"ITEM_FEATHERS": "깃털", "ITEM_LEATHER_SCRAPS": "가죽 조각", "ITEM_DEER_HIDE": "사슴 가죽",
	"ITEM_TROLL_HIDE": "트롤 가죽", "ITEM_WOLF_PELT": "늑대 모피", "ITEM_LOX_PELT": "록스 모피",
	"ITEM_SCALE_HIDE": "비늘 가죽", "ITEM_CARAPACE": "갑각", "ITEM_GREYDWARF_EYE": "회색난쟁이의 눈",
	"ITEM_RESIN_LUMP": "송진 덩어리", "ITEM_ANCIENT_SEED": "고대의 씨앗",
	"ITEM_SURTLING_CORE": "수르틀링 핵", "ITEM_WITHERED_BONE": "말라붙은 뼈",
	"ITEM_BONE_FRAGMENTS": "뼛조각", "ITEM_GUCK": "구크", "ITEM_CHAIN": "쇠사슬",
	"ITEM_ENTRAILS": "내장", "ITEM_OBSIDIAN": "흑요석", "ITEM_FREEZE_GLAND": "냉기 분비선",
	"ITEM_WOLF_FANG": "늑대 송곳니", "ITEM_DRAGON_EGG": "용의 알", "ITEM_CRYSTAL": "수정",
	"ITEM_THISTLE": "엉겅퀴", "ITEM_BLACK_CORE": "검은 핵", "ITEM_SOFT_TISSUE": "연조직",
	"ITEM_SAP": "수액", "ITEM_EITR": "에이트르", "ITEM_MANDIBLE": "큰턱",
	"ITEM_CHARRED_BONE": "그을린 뼈", "ITEM_BLOOD_CLOT": "혈괴", "ITEM_MORGEN_SINEW": "모르겐 힘줄",
	"ITEM_NEEDLE": "바늘", "ITEM_LINEN_THREAD": "아마 실", "ITEM_FLAX": "아마",
	"ITEM_BARLEY": "보리", "ITEM_BARLEY_FLOUR": "보릿가루", "ITEM_COAL": "석탄",
	"ITEM_IRON_NAILS": "철못", "ITEM_BRONZE_NAILS": "청동못", "ITEM_BLOODBAG": "핏주머니",
	"ITEM_DANDELION": "민들레",
	"ITEM_CARROT_SEEDS": "당근 씨앗", "ITEM_TURNIP_SEEDS": "순무 씨앗",
	"ITEM_ONION_SEEDS": "양파 씨앗", "ITEM_BEECH_SEEDS": "너도밤나무 씨앗",
	"ITEM_PINE_CONE": "솔방울",

	# ── 광물 ──
	"ITEM_COPPER_ORE": "구리 원석", "ITEM_TIN_ORE": "주석 원석", "ITEM_IRON_SCRAP": "고철",
	"ITEM_SILVER_ORE": "은 원석", "ITEM_BLACK_METAL_SCRAP": "흑금속 조각",
	"ITEM_FLAMETAL_ORE": "화염금속 원석", "ITEM_COPPER": "구리", "ITEM_TIN": "주석",
	"ITEM_BRONZE": "청동", "ITEM_IRON": "철", "ITEM_SILVER": "은",
	"ITEM_BLACK_METAL": "흑금속", "ITEM_FLAMETAL": "화염금속",

	# ── 보스 드롭 ──
	"ITEM_HARD_ANTLER": "단단한 뿔", "ITEM_SWAMP_KEY": "늪의 열쇠", "ITEM_WISHBONE": "차골",
	"ITEM_DRAGON_TEAR": "용의 눈물", "ITEM_TORN_SPIRIT": "찢긴 영혼",
	"ITEM_QUEEN_DROP": "여왕의 정수", "ITEM_EMBER": "꺼지지 않는 불씨",
	"ITEM_WISHBONE_D": "가까이 묻힌 보물과 광맥을 감지한다.",

	# ── 트로피 ──
	"ITEM_TROPHY_DEER": "사슴 트로피", "ITEM_TROPHY_BOAR": "멧돼지 트로피",
	"ITEM_TROPHY_NECK": "넥 트로피", "ITEM_TROPHY_GREYLING": "그레이링 트로피",
	"ITEM_TROPHY_GREYDWARF": "회색난쟁이 트로피", "ITEM_TROPHY_TROLL": "트롤 트로피",
	"ITEM_TROPHY_SKELETON": "해골 트로피", "ITEM_TROPHY_DRAUGR": "드라우그 트로피",
	"ITEM_TROPHY_BLOB": "블롭 트로피", "ITEM_TROPHY_WRAITH": "망령 트로피",
	"ITEM_TROPHY_WOLF": "늑대 트로피", "ITEM_TROPHY_DRAKE": "드레이크 트로피",
	"ITEM_TROPHY_GOLEM": "골렘 트로피", "ITEM_TROPHY_FULING": "풀링 트로피",
	"ITEM_TROPHY_LOX": "록스 트로피", "ITEM_TROPHY_DEATHSQUITO": "데스스퀴토 트로피",
	"ITEM_TROPHY_SEEKER": "시커 트로피", "ITEM_TROPHY_EIKTHYR": "에이크시르 트로피",
	"ITEM_TROPHY_ELDER": "고목의 왕 트로피", "ITEM_TROPHY_BONEMASS": "본매스 트로피",
	"ITEM_TROPHY_MODER": "모데르 트로피", "ITEM_TROPHY_YAGLUTH": "야글루스 트로피",
	"ITEM_TROPHY_QUEEN": "여왕 트로피",

	# ── 음식 ──
	"ITEM_RASPBERRIES": "산딸기", "ITEM_BLUEBERRIES": "블루베리", "ITEM_MUSHROOM": "버섯",
	"ITEM_CARROT": "당근", "ITEM_TURNIP": "순무", "ITEM_ONION": "양파", "ITEM_HONEY": "꿀",
	"ITEM_CLOUDBERRY": "클라우드베리",
	"ITEM_NECK_TAIL": "넥 꼬리", "ITEM_COOKED_NECK_TAIL": "구운 넥 꼬리",
	"ITEM_BOAR_MEAT": "멧돼지 고기", "ITEM_COOKED_BOAR_MEAT": "구운 멧돼지 고기",
	"ITEM_DEER_MEAT": "사슴 고기", "ITEM_COOKED_DEER_MEAT": "구운 사슴 고기",
	"ITEM_WOLF_MEAT": "늑대 고기", "ITEM_COOKED_WOLF_MEAT": "구운 늑대 고기",
	"ITEM_LOX_MEAT": "록스 고기", "ITEM_COOKED_LOX_MEAT": "구운 록스 고기",
	"ITEM_SERPENT_MEAT": "바다뱀 고기", "ITEM_COOKED_SERPENT_MEAT": "구운 바다뱀 고기",
	"ITEM_FISH": "생선", "ITEM_COOKED_FISH": "구운 생선", "ITEM_QUEENS_JAM": "여왕의 잼",
	"ITEM_BREAD": "빵", "ITEM_CARROT_SOUP": "당근 수프", "ITEM_TURNIP_STEW": "순무 스튜",
	"ITEM_ONION_SOUP": "양파 수프", "ITEM_SAUSAGES": "소시지", "ITEM_BLOOD_PUDDING": "블러드 푸딩",
	"ITEM_LOX_PIE": "록스 파이", "ITEM_FISH_WRAPS": "생선 랩", "ITEM_EITR_BREAD": "에이트르 빵",
	"ITEM_MEAD_HEALTH": "회복의 벌꿀술", "ITEM_MEAD_STAMINA": "기력의 벌꿀술",
	"ITEM_MEAD_POISON": "해독의 벌꿀술", "ITEM_MEAD_FROST": "내한의 벌꿀술",
	"ITEM_MEAD_FIRE": "내화의 벌꿀술",

	# ── 도구 ──
	"ITEM_HAMMER": "망치", "ITEM_HAMMER_D": "장착하면 건축 모드가 된다.",
	"ITEM_HOE": "괭이", "ITEM_CULTIVATOR": "쟁기", "ITEM_TORCH": "횃불",
	"ITEM_ANTLER_PICKAXE": "뿔 곡괭이", "ITEM_BRONZE_PICKAXE": "청동 곡괭이",
	"ITEM_IRON_PICKAXE": "철 곡괭이", "ITEM_BLACKMETAL_PICKAXE": "흑금속 곡괭이",

	# ── 무기 ──
	"ITEM_CLUB": "몽둥이", "ITEM_STONE_AXE": "돌도끼", "ITEM_FLINT_AXE": "부싯돌 도끼",
	"ITEM_FLINT_SPEAR": "부싯돌 창", "ITEM_FLINT_KNIFE": "부싯돌 단검",
	"ITEM_BRONZE_AXE": "청동 도끼", "ITEM_BRONZE_SWORD": "청동 검",
	"ITEM_BRONZE_MACE": "청동 철퇴", "ITEM_BRONZE_ATGEIR": "청동 아트게일",
	"ITEM_IRON_AXE": "철 도끼", "ITEM_IRON_SWORD": "철 검", "ITEM_IRON_MACE": "철 철퇴",
	"ITEM_IRON_ATGEIR": "철 아트게일", "ITEM_IRON_SPEAR": "철 창",
	"ITEM_SILVER_SWORD": "은 검", "ITEM_SILVER_MACE": "은 철퇴", "ITEM_FROSTNER": "프로스트너",
	"ITEM_BLACKMETAL_SWORD": "흑금속 검", "ITEM_BLACKMETAL_AXE": "흑금속 도끼",
	"ITEM_BLACKMETAL_ATGEIR": "흑금속 아트게일", "ITEM_MISTWALKER": "안개걸음",
	"ITEM_FLAMETAL_GREATSWORD": "화염금속 대검",
	"ITEM_CRUDE_BOW": "조잡한 활", "ITEM_FINEWOOD_BOW": "고급 목재 활",
	"ITEM_HUNTSMAN_BOW": "사냥꾼의 활", "ITEM_DRAUGR_FANG": "드라우그의 송곳니",
	"ITEM_SPINE_SNAP": "척추 파쇄궁",
	"ITEM_WOOD_ARROW": "나무 화살", "ITEM_FLINT_ARROW": "부싯돌 화살",
	"ITEM_FIRE_ARROW": "화염 화살", "ITEM_BRONZE_ARROW": "청동 화살",
	"ITEM_IRON_ARROW": "철 화살", "ITEM_POISON_ARROW": "독 화살",
	"ITEM_OBSIDIAN_ARROW": "흑요석 화살", "ITEM_FROST_ARROW": "냉기 화살",
	"ITEM_NEEDLE_ARROW": "바늘 화살",

	# ── 방패 ──
	"ITEM_WOOD_SHIELD": "나무 방패", "ITEM_BANDED_SHIELD": "테두른 방패",
	"ITEM_IRON_BUCKLER": "철 버클러", "ITEM_SILVER_SHIELD": "은 방패",
	"ITEM_BLACKMETAL_SHIELD": "흑금속 방패", "ITEM_CARAPACE_BUCKLER": "갑각 버클러",

	# ── 방어구 ──
	"ITEM_RAG_HOOD": "누더기 두건", "ITEM_RAG_TUNIC": "누더기 상의",
	"ITEM_LEATHER_HELMET": "가죽 투구", "ITEM_LEATHER_TUNIC": "가죽 갑옷",
	"ITEM_LEATHER_PANTS": "가죽 바지", "ITEM_TROLL_HOOD": "트롤 가죽 두건",
	"ITEM_TROLL_TUNIC": "트롤 가죽 상의", "ITEM_TROLL_PANTS": "트롤 가죽 바지",
	"ITEM_BRONZE_HELMET": "청동 투구", "ITEM_BRONZE_CUIRASS": "청동 흉갑",
	"ITEM_BRONZE_GREAVES": "청동 각반", "ITEM_IRON_HELMET": "철 투구",
	"ITEM_IRON_SCALE_MAIL": "철 비늘갑옷", "ITEM_IRON_GREAVES": "철 각반",
	"ITEM_WOLF_HEADDRESS": "늑대 머리장식", "ITEM_WOLF_ARMOR_CHEST": "늑대 갑옷",
	"ITEM_WOLF_ARMOR_LEGS": "늑대 각반", "ITEM_PADDED_HELMET": "누비 투구",
	"ITEM_PADDED_CUIRASS": "누비 흉갑", "ITEM_PADDED_GREAVES": "누비 각반",
	"ITEM_CARAPACE_HELMET": "갑각 투구", "ITEM_CARAPACE_BREASTPLATE": "갑각 흉갑",
	"ITEM_CARAPACE_LEGGUARDS": "갑각 각반",
	"ITEM_DEER_CAPE": "사슴 가죽 망토", "ITEM_TROLL_CAPE": "트롤 가죽 망토",
	"ITEM_WOLF_CAPE": "늑대 모피 망토", "ITEM_LOX_CAPE": "록스 모피 망토",
	"ITEM_FEATHER_CAPE": "깃털 망토",
	"ITEM_WOLF_CAPE_D": "혹한을 완전히 막아준다.",
	"ITEM_LOX_CAPE_D": "혹한을 완전히 막아준다.",
	"ITEM_FEATHER_CAPE_D": "낙하 피해를 받지 않는다.",

	# ── 건축 조각 ──
	"PIECE_CAMPFIRE": "모닥불", "PIECE_WORKBENCH": "작업대", "PIECE_CHEST": "상자",
	"PIECE_CHEST_LARGE": "큰 상자", "PIECE_BED": "침대", "PIECE_PORTAL": "차원문",
	"PIECE_SIGN": "표지판",
	"PIECE_RAFT": "뗏목", "PIECE_KARVE": "카르베", "PIECE_LONGSHIP": "롱십",
	"PIECE_WOOD_FLOOR": "나무 바닥", "PIECE_WOOD_WALL": "나무 벽",
	"PIECE_WOOD_WALL_HALF": "나무 반벽", "PIECE_WOOD_BEAM": "나무 들보",
	"PIECE_WOOD_BEAM_26": "경사 들보", "PIECE_WOOD_POLE": "나무 기둥",
	"PIECE_WOOD_ROOF": "나무 지붕", "PIECE_WOOD_ROOF_TOP": "지붕 마루",
	"PIECE_WOOD_DOOR": "나무 문", "PIECE_WOOD_STAIR": "나무 계단",
	"PIECE_WOOD_LADDER": "사다리", "PIECE_WOOD_FENCE": "나무 울타리",
	"PIECE_STONE_FLOOR": "석재 바닥", "PIECE_STONE_WALL": "석벽",
	"PIECE_STONE_PILLAR": "석주", "PIECE_STONE_STAIR": "석재 계단",
	"PIECE_HEARTH": "화덕", "PIECE_TORCH_STAND": "횃불대", "PIECE_CHAIR": "의자",
	"PIECE_TABLE": "탁자", "PIECE_BANNER": "깃발", "PIECE_RUG_DEER": "사슴 가죽 깔개",
	"PIECE_FORGE": "대장간", "PIECE_CAULDRON": "가마솥", "PIECE_COOKING_STATION": "요리 화로",
	"PIECE_SMELTER": "제련소", "PIECE_CHARCOAL_KILN": "숯가마",
	"PIECE_BLAST_FURNACE": "용광로", "PIECE_WINDMILL": "풍차",
	"PIECE_SPINNING_WHEEL": "물레", "PIECE_ARTISAN_TABLE": "장인의 탁자",
	"PIECE_STONECUTTER": "석공대", "PIECE_FERMENTER": "발효조",
	"PIECE_WB_CHOPPING_BLOCK": "장작 받침", "PIECE_WB_TANNING_RACK": "무두질 틀",
	"PIECE_WB_ADZE": "손도끼대", "PIECE_WB_TOOL_SHELF": "공구 선반",
	"PIECE_FORGE_BELLOWS": "풀무", "PIECE_FORGE_ANVILS": "모루",
	"PIECE_FORGE_GRINDSTONE": "숫돌", "PIECE_FORGE_TOOLRACK": "대장간 공구대",
	"PIECE_PLANT_CARROT": "당근 심기", "PIECE_PLANT_TURNIP": "순무 심기",
	"PIECE_PLANT_ONION": "양파 심기", "PIECE_PLANT_BARLEY": "보리 심기",
	"PIECE_PLANT_FLAX": "아마 심기", "PIECE_PLANT_BEECH": "너도밤나무 심기",
	"PIECE_PLANT_PINE": "소나무 심기",

	# ── 몬스터 ──
	"MOB_GREYLING": "그레이링", "MOB_NECK": "넥", "MOB_BOAR": "멧돼지", "MOB_DEER": "사슴",
	"MOB_GREYDWARF": "회색난쟁이", "MOB_GREYDWARF_BRUTE": "회색난쟁이 광폭전사",
	"MOB_GREYDWARF_SHAMAN": "회색난쟁이 주술사", "MOB_TROLL": "트롤", "MOB_SKELETON": "해골",
	"MOB_DRAUGR": "드라우그", "MOB_DRAUGR_ELITE": "정예 드라우그", "MOB_BLOB": "블롭",
	"MOB_OOZER": "우저", 
	"MOB_WOLF": "늑대", "MOB_FENRING": "펜링", "MOB_DRAKE": "드레이크",
	"MOB_STONE_GOLEM": "석상 골렘", "MOB_FULING": "풀링", "MOB_FULING_BERSERKER": "풀링 광전사",
	"MOB_DEATHSQUITO": "데스스퀴토", "MOB_LOX": "록스",
	"MOB_SEEKER": "시커", "MOB_SEEKER_SOLDIER": "시커 병사", "MOB_GJALL": "걀",
	"MOB_TICK": "진드기", "MOB_CHARRED_WARRIOR": "그을린 전사", "MOB_MORGEN": "모르겐",
	"MOB_VOLTURE": "볼처",

	# ── 보스 ──
	"BOSS_EIKTHYR": "에이크시르", "BOSS_ELDER": "고목의 왕", "BOSS_BONEMASS": "본매스",
	"BOSS_MODER": "모데르", "BOSS_YAGLUTH": "야글루스", "BOSS_QUEEN": "안개의 여왕",
	"BOSS_FADER": "파데르",

	# ── 포세이큰 파워 ──
	"POWER_EIKTHYR": "에이크시르의 힘", "POWER_EIKTHYR_D": "달리기와 도약의 기력 소모가 크게 줄어든다.",
	"POWER_ELDER": "고목의 왕의 힘", "POWER_ELDER_D": "받는 피해가 크게 감소한다.",
	"POWER_BONEMASS": "본매스의 힘", "POWER_BONEMASS_D": "물리 저항이 상승한다.",
	"POWER_MODER": "모데르의 힘", "POWER_MODER_D": "항상 순풍이 불고 낙하 피해가 준다.",
	"POWER_YAGLUTH": "야글루스의 힘", "POWER_YAGLUTH_D": "이동 속도가 빨라진다.",
	"POWER_QUEEN": "여왕의 힘", "POWER_QUEEN_D": "에이트르 회복이 빨라진다.",
	"POWER_FADER": "파데르의 힘", "POWER_FADER_D": "화염 저항이 크게 오른다.",

	# ── 제작대 ──
	"STATION_WORKBENCH": "작업대", "STATION_FORGE": "대장간", "STATION_CAULDRON": "가마솥",
	"STATION_ARTISAN_TABLE": "장인의 탁자", "STATION_STONECUTTER": "석공대",

	# ── 날씨 ──
	"WEATHER_CLEAR": "맑음", "WEATHER_CLOUDY": "흐림", "WEATHER_RAIN": "비",
	"WEATHER_STORM": "폭풍우", "WEATHER_SNOW": "눈보라", "WEATHER_MIST": "짙은 안개",
	"WEATHER_ASHFALL": "잿비",

	# ── 상태이상 ──
	"STATUS_WET": "젖음", "STATUS_COLD": "추움", "STATUS_FREEZING": "혹한",
	"STATUS_POISON": "중독", "STATUS_BURNING": "화상", "STATUS_RESTED": "휴식",
	"STATUS_RES_FIRE": "화염 저항", "STATUS_RES_FROST": "냉기 저항",
	"STATUS_RES_POISON": "독 저항",

	# ── 장비 슬롯 ──
	"SLOT_HEAD": "머리", "SLOT_CHEST": "몸통", "SLOT_LEGS": "다리", "SLOT_CAPE": "망토",
	"SLOT_RIGHT": "주무기", "SLOT_LEFT": "보조", "SLOT_AMMO": "탄약",

	# ── UI ──
	"UI_INVENTORY": "소지품", "UI_CRAFTING": "제작", "UI_HANDCRAFT": "맨손 제작",
	"UI_CHEST": "상자", "UI_TOMBSTONE": "무덤", "UI_MAP": "지도", "UI_SKILLS": "숙련도",
	"UI_STATS": "기록", "UI_POWERS": "포세이큰 파워", "UI_PAUSED": "일시정지",
	"UI_RESUME": "계속하기", "UI_SAVE": "저장 (F5)", "UI_LOAD": "불러오기 (F9)",
	"UI_QUIT": "저장 후 종료", "UI_YOU_DIED": "그대는 쓰러졌다",
	"UI_DEATH_DESC": "소지품은 쓰러진 자리에 무덤으로 남았다. 모든 숙련도가 5% 감소했다.",
	"UI_RESPAWN": "부활", "UI_CRAFT": "제작하기", "UI_UPGRADE": "강화하기",
	"UI_TAB_CRAFT": "제작", "UI_TAB_UPGRADE": "강화",
	"UI_NO_RECIPES": "이 제작대에서 만들 수 있는 것이 없다.",
	"UI_NO_UPGRADES": "강화할 수 있는 장비가 없다.",
	"UI_SELECT_RECIPE": "왼쪽에서 항목을 고르시오.",
	"UI_DAY": "%d일차", "UI_WEIGHT": "무게 %d / %d", "UI_ARMOR": "방어도 %d",
	"UI_WEIGHT_ONE": "무게 %.1f", "UI_NO_TELEPORT": "차원문으로 옮길 수 없다",
	"UI_QUALITY": "품질 %d / %d",
	"UI_ATTACK_SPEED": "공격 속도: %.2f", "UI_STAMINA_COST": "기력 소모: %d",
	"UI_BLOCK_POWER": "방어력: %d", "UI_PARRY": "패링 배수: %.1f",
	"UI_ARMOR_VALUE": "방어도: %d", "UI_FOOD_HP": "최대 체력 +%d",
	"UI_FOOD_SP": "최대 기력 +%d", "UI_FOOD_TIME": "지속 %d분",
	"UI_FOOD_REGEN": "체력 재생 %.1f", "UI_TOOL_TIER": "채광 등급 %d",
	"UI_CHOP_TIER": "벌목 등급 %d",
	"UI_INV_HINT": "좌클릭: 집기/놓기 · 우클릭: 착용/사용 · Shift+좌클릭: 상자로 이동",
	"UI_CAT_MISC": "잡화", "UI_CAT_WOOD": "목재", "UI_CAT_STONE": "석재",
	"UI_CAT_FURNITURE": "가구", "UI_CAT_STATIONS": "시설", "UI_CAT_UPGRADES": "부속",
	"UI_CAT_FARMING": "농사",
	"UI_BUILD_HINT": "선택: %s",
	"UI_BUILD_KEYS": "좌클릭 설치 · 우클릭 철거 · R 회전",
	"UI_NEEDS_WORKBENCH": "작업대 근처에서만 설치 가능",
	"UI_NEEDS_FUEL": "석탄 부족", "UI_BURNT": "탔음", "UI_COOKED": "완성",
	"UI_NO_POWERS": "아직 얻은 힘이 없다. 보스를 쓰러뜨리시오.",
	"UI_POWER_HINT": "F 키로 발동 (재사용 대기 5분)",
	"UI_CONTROLS": "WASD 이동 · Shift 달리기 · Space 점프 · Ctrl 웅크리기 · Alt 구르기\nE 상호작용 · Tab 소지품 · M 지도 · K 숙련도 · P 파워 · B/망치 건축\n좌클릭 공격 · 우클릭 방어 · 1~8 단축바",
	# ── 멀티플레이 ──
	"UI_MULTIPLAYER": "멀티플레이", "UI_HOST": "호스트 열기", "UI_JOIN": "접속",
	"UI_IP": "주소", "UI_PORT": "포트", "UI_NICKNAME": "이름",
	"UI_CHAT": "채팅", "UI_CHAT_HINT": "Enter 로 전송, Esc 로 닫기",
	"UI_PLAYERS_ONLINE": "접속자",
	"NET_OFFLINE": "싱글플레이", "NET_HOSTING": "호스트", "NET_CLIENT": "클라이언트",
	"NET_PLAYERS": "%d명 접속",
	"MSG_NET_HOSTING": "포트 %d 에서 호스트를 열었다.",
	"MSG_NET_HOST_FAIL": "호스트를 열지 못했다 (오류 %d).",
	"MSG_NET_CONNECTING": "%s 에 접속하는 중...",
	"MSG_NET_CONNECTED": "서버에 접속했다.",
	"MSG_NET_JOIN_FAIL": "접속에 실패했다.",
	"MSG_NET_SERVER_GONE": "서버와의 연결이 끊겼다.",
	"MSG_NET_JOINED_PEER": "%s 님이 들어왔다.",
	"MSG_NET_LEFT_PEER": "%s 님이 나갔다.",
	# ── 확장 콘텐츠 (아이템 이름) ──
	"ITEM_BIRCH_SEEDS": "자작나무 씨앗", "ITEM_FIR_CONE": "전나무 솔방울", "ITEM_RASPBERRY_SEEDS": "산딸기 씨앗",
	"ITEM_VINE_SEEDS": "덩굴 씨앗", "ITEM_JUTE_RED": "붉은 황마", "ITEM_JUTE_BLUE": "푸른 황마",
	"ITEM_LEATHER_BELT": "가죽 허리띠", "ITEM_WISP": "윌오위스프", "ITEM_ROOT": "뿌리",
	"ITEM_IRON_INGOT_SCRAP": "철 조각쇠", "ITEM_TAR": "타르", "ITEM_BAT_WING": "박쥐 날개",
	"ITEM_SERPENT_SCALE": "바다뱀 비늘", "ITEM_SERPENT_TROPHY_SCALE": "바다뱀 큰비늘", "ITEM_BONE_MASS": "뼈 덩어리",
	"ITEM_CHITIN": "키틴", "ITEM_MARBLE": "대리석", "ITEM_GRAUSTEN": "회암",
	"ITEM_CERAMIC_PLATE": "도자판", "ITEM_PROUSTITE": "담홍은석", "ITEM_RUBY": "루비",
	"ITEM_AMBER": "호박", "ITEM_AMBER_PEARL": "호박 진주", "ITEM_COINS": "금화",
	"ITEM_SILVER_NECKLACE": "은목걸이", "ITEM_PERCH": "농어", "ITEM_PIKE": "강꼬치고기",
	"ITEM_TUNA": "참치", "ITEM_TROLLFISH": "트롤피시", "ITEM_MAGMAFISH": "용암어",
	"ITEM_NORTHERN_SALMON": "북방 연어", "ITEM_COOKED_PERCH": "구운 농어", "ITEM_COOKED_PIKE": "구운 강꼬치고기",
	"ITEM_COOKED_TUNA": "구운 참치", "ITEM_COOKED_MAGMAFISH": "구운 용암어", "ITEM_GRILLED_NECK_TAIL": "넥꼬리 구이",
	"ITEM_HONEY_GLAZED_CHICKEN": "꿀 발린 닭구이", "ITEM_BOAR_JERKY": "멧돼지 육포", "ITEM_DEER_STEW": "사슴 스튜",
	"ITEM_MINCED_MEAT_SAUCE": "다진 고기 소스", "ITEM_BREAD_AND_HONEY": "꿀 바른 빵", "ITEM_MUSHROOM_STEW": "버섯 스튜",
	"ITEM_BERRY_PIE": "산딸기 파이", "ITEM_WOLF_SKEWER": "늑대고기 꼬치", "ITEM_SERPENT_STEW": "바다뱀 스튜",
	"ITEM_FISH_AND_BREAD": "생선 빵", "ITEM_BLOOD_SAUSAGE": "피 소시지", "ITEM_MISTHARE_SUPREME": "안개토끼 별미",
	"ITEM_YGGDRASIL_PORRIDGE": "위그드라실 죽", "ITEM_SEEKER_ASPIC": "탐색자 묵", "ITEM_MEAD_TASTY": "맛있는 벌꿀술",
	"ITEM_MEAD_MEDIUM_HEALTH": "중급 치유 벌꿀술", "ITEM_MEAD_MINOR_EITR": "하급 에이트르 벌꿀술", "ITEM_MEAD_LINGERING_STAMINA": "지속 기력 벌꿀술",
	"ITEM_MEAD_BZERKER": "광전사 벌꿀술", "ITEM_WOOD_CLUB": "나무 몽둥이", "ITEM_BONE_KNIFE": "뼈 단검",
	"ITEM_BRONZE_KNIFE": "청동 단검", "ITEM_IRON_KNIFE": "철 단검", "ITEM_SILVER_KNIFE": "은 단검",
	"ITEM_BLACKMETAL_KNIFE": "흑금속 단검", "ITEM_BRONZE_SPEAR": "청동 창", "ITEM_ANCIENT_BARK_SPEAR": "고대나무 창",
	"ITEM_BLACKMETAL_SPEAR": "흑금속 창", "ITEM_BATTLEAXE_CRYSTAL": "수정 전투도끼", "ITEM_PORCUPINE": "호저",
	"ITEM_DAGGER_DYRNWYN": "디른윈", "ITEM_STAGBREAKER": "사슴잡이", "ITEM_CRYSTAL_BATTLEAXE": "수정 대도끼",
	"ITEM_BONE_ARROW": "뼈 화살", "ITEM_SILVER_ARROW": "은 화살", "ITEM_CARAPACE_ARROW": "갑각 화살",
	"ITEM_FLAMETAL_ARROW": "화염금속 화살", "ITEM_BRONZE_BUCKLER": "청동 소형방패", "ITEM_BONE_TOWER_SHIELD": "뼈 대형방패",
	"ITEM_SERPENT_SCALE_SHIELD": "바다뱀 비늘 방패", "ITEM_FLAMETAL_SHIELD": "화염금속 방패", "ITEM_ROOT_MASK": "뿌리 가면",
	"ITEM_ROOT_HARNESK": "뿌리 갑주", "ITEM_ROOT_LEGGINGS": "뿌리 각반", "ITEM_LINEN_HOOD": "린넨 두건",
	"ITEM_FENRIS_HOOD": "펜리르 두건", "ITEM_FENRIS_COAT": "펜리르 외투", "ITEM_FENRIS_LEGGINGS": "펜리르 바지",
	"ITEM_EITR_WEAVE_HOOD": "에이트르 직조 두건", "ITEM_EITR_WEAVE_ROBE": "에이트르 직조 로브", "ITEM_EITR_WEAVE_TROUSERS": "에이트르 직조 바지",
	"ITEM_FLAMETAL_HELMET": "화염금속 투구", "ITEM_FLAMETAL_CUIRASS": "화염금속 흉갑", "ITEM_FLAMETAL_GREAVES": "화염금속 각반",
	"ITEM_LINEN_CAPE": "린넨 망토", "ITEM_ASH_CAPE": "잿불 망토", "ITEM_TROPHY_SERPENT": "바다뱀 트로피",
	"ITEM_TROPHY_LEECH": "거머리 트로피", "ITEM_TROPHY_SURTLING": "수르틀링 트로피", "ITEM_TROPHY_BAT": "박쥐 트로피",
	"ITEM_TROPHY_HARE": "안개토끼 트로피", "ITEM_TROPHY_GJALL": "걀 트로피", "ITEM_TROPHY_TICK": "진드기 트로피",
	"ITEM_TROPHY_DVERGR": "드베르그 트로피", "ITEM_TROPHY_ASKSVIN": "아스크스빈 트로피", "ITEM_TROPHY_CHARRED": "잿불병사 트로피",
	"ITEM_TROPHY_FADER": "파데르 트로피",
	# ── 확장 생물 ──
	"MOB_CHICKEN": "닭", "MOB_BAT": "박쥐", 
	"MOB_SERPENT": "바다뱀", "MOB_HARE": "안개토끼",
	"MOB_DVERGR": "드베르그", "MOB_ASKSVIN": "아스크스빈", "MOB_CHARRED_ARCHER": "잿불 궁수",
	"MOB_SKELETON_ARCHER": "해골 궁수", 
	"MOB_SURTLING": "수르틀링", "MOB_LEECH": "거머리", "MOB_WRAITH": "망령",
	"MOB_FULING_SHAMAN": "풀링 주술사",
	# ── 룬석 전승 ──
	"UI_RUNESTONE": "룬석", "PROMPT_READ_RUNESTONE": "[E] 룬석 읽기",
	"LORE_1": "「오딘이 우리를 이곳에 보냈다. 열 번째 세계, 심판받지 못한 자들의 땅으로.」",
	"LORE_2": "「사슴뿔을 쓴 자가 숲을 다스린다. 그 발굽 소리가 들리면 활을 들어라.」",
	"LORE_3": "「우리는 늪에서 철을 캤다. 그 대가로 절반이 돌아오지 못했다.」",
	"LORE_4": "「산 위에는 아무것도 자라지 않는다. 오직 추위와, 추위를 견디는 것들만.」",
	"LORE_5": "「평원의 풀은 사람 키를 넘고, 그 사이에 눈이 셋 달린 것들이 숨는다.」",
	"LORE_6": "「안개 속에서는 소리를 믿지 마라. 안개가 소리를 흉내 낸다.」",
	"LORE_7": "「불의 땅에서는 돌도 탄다. 우리가 남긴 것은 재뿐이다.」",
	"LORE_8": "「다섯 제단에 공물을 바쳐라. 그러면 문이 열린다 — 그것이 축복인지는 모르겠다.」",
	"LORE_9": "「나는 서른일곱 번 죽었고 서른일곱 번 돌아왔다. 그것이 형벌이다.」",
	"LORE_10": "「발할라는 이 너머에 있다. 여기서 죽는 것으로는 갈 수 없다.」",
	"UI_TITLE": "발할라",
	"UI_SUBTITLE": "북유럽 서바이벌 — 발헤임에 바치는 오마주",
	"UI_NEW_GAME": "새 세계", "UI_CONTINUE": "이어하기", "UI_SEED": "시드",
	"UI_RANDOM_SEED": "무작위", "UI_START": "시작", "UI_LOADING": "세계를 빚는 중...",
	"UI_EXIT": "종료",

	# ── 안내문 ──
	"PROMPT_PICK": "%s 줍기", "PROMPT_OPEN": "%s 열기", "PROMPT_TAKE_ALL": "모두 회수",
	"PROMPT_DOOR": "문 여닫기", "PROMPT_SLEEP": "잠자기", "PROMPT_SIT": "앉기",
	"PROMPT_COOK": "요리하기", "PROMPT_INSERT": "재료 넣기", "PROMPT_CRAFT": "제작하기",
	"PROMPT_HARVEST": "수확하기", "PROMPT_PORTAL": "차원문 사용",
	"PROMPT_OFFER": "%s 에게 공물 바치기 (%s)",
	"PROMPT_EMBARK": "%s 에 타기", "PROMPT_DISEMBARK": "내리기",

	# ── 메시지 ──
	"MSG_YOU_DIED": "그대는 쓰러졌다...", "MSG_TOO_WEAK": "도구가 약하다",
	"MSG_BLOCKED": "막았다!", "MSG_PARRY": "패링!", "MSG_STAGGERED": "휘청!",
	"MSG_SKILL_UP": "%s 숙련도 %d 달성", "MSG_NEW_DAY": "%d일차 아침이 밝았다",
	"MSG_CRAFTED": "%s 을(를) 만들었다", "MSG_UPGRADED": "%s 을(를) ★%d 로 강화했다",
	"MSG_NOT_ENOUGH": "재료가 모자라다", "MSG_INVENTORY_FULL": "소지품이 가득 찼다",
	"MSG_ATE": "%s 을(를) 먹었다", "MSG_DRANK": "%s 을(를) 마셨다",
	"MSG_TOO_FULL": "지금은 더 먹을 수 없다",
	"MSG_SLEPT": "푹 잤다. 몸이 개운하다.", "MSG_CANT_SLEEP": "밤에만 잘 수 있다",
	"MSG_STATION_FULL": "자리가 없다", "MSG_NOTHING_TO_COOK": "구울 재료가 없다",
	"MSG_NOTHING_TO_SMELT": "제련할 재료가 없다",
	"MSG_NO_PORTAL": "연결된 차원문이 없다",
	"MSG_PORTAL_BLOCKED": "%s 은(는) 차원문을 통과할 수 없다",
	"MSG_NEED_OFFERING": "공물이 부족하다",
	"MSG_BOSS_SUMMONED": "%s 이(가) 깨어났다!",
	"MSG_BOSS_DEFEATED": "%s 을(를) 쓰러뜨렸다! 새로운 힘을 얻었다.",
	"MSG_BOSS_ENRAGED": "%s 이(가) 격노한다!",
	"MSG_BOSS_SUMMONS": "보스가 하수인을 불러낸다!",
	"MSG_POWER_ACTIVATED": "%s 발동!",
	"MSG_RAID": "무언가가 몰려온다...",
	"MSG_SAVED": "저장했다", "MSG_LOADED": "불러왔다", "MSG_NO_SAVE": "저장 파일이 없다",
	"MSG_SAVE_FAILED": "저장에 실패했다", "MSG_SAVE_CORRUPT": "저장 파일이 손상됐다",
	"MSG_LANG_CHANGED": "언어를 바꿨다",
	"MSG_WELCOME": "까마귀가 속삭인다: 불을 피우고, 지붕을 얹고, 살아남으라.",
	"MSG_HOE_LEVEL": "괭이: 평탄화", "MSG_HOE_RAISE": "괭이: 융기", "MSG_HOE_DIG": "괭이: 굴착",
	"MSG_NO_BAIT": "미끼가 없다", "MSG_FISH_BITE": "입질이 왔다! 좌클릭",
	"MSG_FISH_HOOKED": "걸렸다! 좌클릭을 눌러 감아라",
	"MSG_FISH_ESCAPED": "놓쳤다", "MSG_FISH_LOST": "기력이 다해 줄이 끊겼다",
	"MSG_FISH_TOO_SHALLOW": "너무 얕다",
	"MSG_NO_EITR_FOOD": "에이트르가 없다 — 마법 음식을 먹어야 한다",
	"MSG_NOT_ENOUGH_EITR": "에이트르가 모자라다",
	"MSG_SHIELD_UP": "마법 보호막이 감쌌다", "MSG_SUMMONED": "해골을 불러냈다",
	"MSG_TAMED": "%s 을(를) 길들였다", "MSG_TAMING": "%s 이(가) 마음을 열고 있다",
	"MSG_BABY_BORN": "%s 새끼가 태어났다",
	"ITEM_FISHING_ROD": "낚싯대", "ITEM_FISHING_BAIT": "낚시 미끼",
	"ITEM_LEECH_FISH": "거머리 물고기",
	"ITEM_STAFF_FIRE": "화염의 지팡이", "ITEM_STAFF_FROST": "서리의 지팡이",
	"ITEM_STAFF_SHIELD": "보호의 지팡이", "ITEM_STAFF_SKELETON": "해골 소환 지팡이",
	"ITEM_SAP_STEW": "수액 스튜", "ITEM_MUSHROOM_OMELETTE": "버섯 오믈렛",
	"STATUS_MAGIC_SHIELD": "마법 보호막",
	"UI_EITR": "에이트르",
	"DUNGEON_CRYPT": "고대 매장지", "DUNGEON_SUNKEN": "수몰된 묘지",
	"DUNGEON_CAVE": "얼음 동굴", "UI_DUNGEON_EXIT": "출구",
	"PROMPT_ENTER_DUNGEON": "%s 로 들어가기", "PROMPT_EXIT_DUNGEON": "밖으로 나가기",
	"MSG_ENTER_DUNGEON": "축축한 공기와 오래된 돌 냄새가 밀려온다.",
	"MSG_EXIT_DUNGEON": "다시 하늘 아래로 나왔다.",

	"ALTAR_DEFEATED": "%s — 쓰러뜨림",

	"STAT_KILLS": "처치", "STAT_DEATHS": "사망", "STAT_CRAFTED": "제작",
	"STAT_BUILT": "건축", "STAT_TREES": "벌목한 나무", "STAT_DISTANCE": "이동 거리",
}

# ══════════════════════════════════════════════════════════ English
const EN := {
	"BIOME_OCEAN": "Ocean", "BIOME_MEADOWS": "Meadows", "BIOME_BLACKFOREST": "Black Forest",
	"BIOME_SWAMP": "Swamp", "BIOME_MOUNTAIN": "Mountains", "BIOME_PLAINS": "Plains",
	"BIOME_MISTLANDS": "Mistlands", "BIOME_ASHLANDS": "Ashlands",

	"DMG_BLUNT": "Blunt", "DMG_SLASH": "Slash", "DMG_PIERCE": "Pierce", "DMG_CHOP": "Chop",
	"DMG_PICKAXE": "Pickaxe", "DMG_FIRE": "Fire", "DMG_FROST": "Frost", "DMG_POISON": "Poison",
	"DMG_LIGHTNING": "Lightning", "DMG_SPIRIT": "Spirit",

	"SKILL_RUN": "Run", "SKILL_JUMP": "Jump", "SKILL_SWIM": "Swim", "SKILL_SNEAK": "Sneak",
	"SKILL_BLOCK": "Block", "SKILL_AXES": "Axes", "SKILL_CLUBS": "Clubs", "SKILL_SWORDS": "Swords",
	"SKILL_SPEARS": "Spears", "SKILL_KNIVES": "Knives", "SKILL_BOWS": "Bows",
	"SKILL_UNARMED": "Unarmed", "SKILL_PICKAXES": "Pickaxes", "SKILL_WOODCUTTING": "Woodcutting",

	"ITEM_WOOD": "Wood", "ITEM_CORE_WOOD": "Core Wood", "ITEM_FINE_WOOD": "Fine Wood",
	"ITEM_ANCIENT_BARK": "Ancient Bark", "ITEM_YGGDRASIL_WOOD": "Yggdrasil Wood",
	"ITEM_STONE": "Stone", "ITEM_FLINT": "Flint", "ITEM_RESIN": "Resin",
	"ITEM_FEATHERS": "Feathers", "ITEM_LEATHER_SCRAPS": "Leather Scraps",
	"ITEM_DEER_HIDE": "Deer Hide", "ITEM_TROLL_HIDE": "Troll Hide",
	"ITEM_WOLF_PELT": "Wolf Pelt", "ITEM_LOX_PELT": "Lox Pelt", "ITEM_SCALE_HIDE": "Scale Hide",
	"ITEM_CARAPACE": "Carapace", "ITEM_GREYDWARF_EYE": "Greydwarf Eye",
	"ITEM_ANCIENT_SEED": "Ancient Seed", "ITEM_SURTLING_CORE": "Surtling Core",
	"ITEM_WITHERED_BONE": "Withered Bone", "ITEM_BONE_FRAGMENTS": "Bone Fragments",
	"ITEM_GUCK": "Guck", "ITEM_CHAIN": "Chain", "ITEM_ENTRAILS": "Entrails",
	"ITEM_OBSIDIAN": "Obsidian", "ITEM_FREEZE_GLAND": "Freeze Gland",
	"ITEM_WOLF_FANG": "Wolf Fang", "ITEM_DRAGON_EGG": "Dragon Egg", "ITEM_CRYSTAL": "Crystal",
	"ITEM_THISTLE": "Thistle", "ITEM_BLACK_CORE": "Black Core", "ITEM_SOFT_TISSUE": "Soft Tissue",
	"ITEM_SAP": "Sap", "ITEM_EITR": "Eitr", "ITEM_MANDIBLE": "Mandible",
	"ITEM_CHARRED_BONE": "Charred Bone", "ITEM_BLOOD_CLOT": "Blood Clot",
	"ITEM_MORGEN_SINEW": "Morgen Sinew", "ITEM_NEEDLE": "Needle",
	"ITEM_LINEN_THREAD": "Linen Thread", "ITEM_FLAX": "Flax", "ITEM_BARLEY": "Barley",
	"ITEM_BARLEY_FLOUR": "Barley Flour", "ITEM_COAL": "Coal", "ITEM_IRON_NAILS": "Iron Nails",
	"ITEM_BRONZE_NAILS": "Bronze Nails", "ITEM_BLOODBAG": "Blood Bag",
	"ITEM_DANDELION": "Dandelion", "ITEM_RESIN_LUMP": "Resin Lump",
	"ITEM_CARROT_SEEDS": "Carrot Seeds", "ITEM_TURNIP_SEEDS": "Turnip Seeds",
	"ITEM_ONION_SEEDS": "Onion Seeds", "ITEM_BEECH_SEEDS": "Beech Seeds",
	"ITEM_PINE_CONE": "Pine Cone",

	"ITEM_COPPER_ORE": "Copper Ore", "ITEM_TIN_ORE": "Tin Ore", "ITEM_IRON_SCRAP": "Iron Scrap",
	"ITEM_SILVER_ORE": "Silver Ore", "ITEM_BLACK_METAL_SCRAP": "Black Metal Scrap",
	"ITEM_FLAMETAL_ORE": "Flametal Ore", "ITEM_COPPER": "Copper", "ITEM_TIN": "Tin",
	"ITEM_BRONZE": "Bronze", "ITEM_IRON": "Iron", "ITEM_SILVER": "Silver",
	"ITEM_BLACK_METAL": "Black Metal", "ITEM_FLAMETAL": "Flametal",

	"ITEM_HARD_ANTLER": "Hard Antler", "ITEM_SWAMP_KEY": "Swamp Key", "ITEM_WISHBONE": "Wishbone",
	"ITEM_DRAGON_TEAR": "Dragon Tear", "ITEM_TORN_SPIRIT": "Torn Spirit",
	"ITEM_QUEEN_DROP": "Queen's Essence", "ITEM_EMBER": "Everburning Ember",

	"ITEM_RASPBERRIES": "Raspberries", "ITEM_BLUEBERRIES": "Blueberries",
	"ITEM_MUSHROOM": "Mushroom", "ITEM_CARROT": "Carrot", "ITEM_TURNIP": "Turnip",
	"ITEM_ONION": "Onion", "ITEM_HONEY": "Honey", "ITEM_CLOUDBERRY": "Cloudberry",
	"ITEM_NECK_TAIL": "Neck Tail", "ITEM_COOKED_NECK_TAIL": "Grilled Neck Tail",
	"ITEM_BOAR_MEAT": "Boar Meat", "ITEM_COOKED_BOAR_MEAT": "Cooked Boar Meat",
	"ITEM_DEER_MEAT": "Deer Meat", "ITEM_COOKED_DEER_MEAT": "Cooked Deer Meat",
	"ITEM_WOLF_MEAT": "Wolf Meat", "ITEM_COOKED_WOLF_MEAT": "Cooked Wolf Meat",
	"ITEM_LOX_MEAT": "Lox Meat", "ITEM_COOKED_LOX_MEAT": "Cooked Lox Meat",
	"ITEM_SERPENT_MEAT": "Serpent Meat", "ITEM_COOKED_SERPENT_MEAT": "Serpent Stew",
	"ITEM_FISH": "Fish", "ITEM_COOKED_FISH": "Cooked Fish", "ITEM_QUEENS_JAM": "Queen's Jam",
	"ITEM_BREAD": "Bread", "ITEM_CARROT_SOUP": "Carrot Soup", "ITEM_TURNIP_STEW": "Turnip Stew",
	"ITEM_ONION_SOUP": "Onion Soup", "ITEM_SAUSAGES": "Sausages",
	"ITEM_BLOOD_PUDDING": "Blood Pudding", "ITEM_LOX_PIE": "Lox Pie",
	"ITEM_FISH_WRAPS": "Fish Wraps", "ITEM_EITR_BREAD": "Eitr Bread",
	"ITEM_MEAD_HEALTH": "Mead: Healing", "ITEM_MEAD_STAMINA": "Mead: Stamina",
	"ITEM_MEAD_POISON": "Mead: Poison Resist", "ITEM_MEAD_FROST": "Mead: Frost Resist",
	"ITEM_MEAD_FIRE": "Mead: Fire Resist",

	"ITEM_HAMMER": "Hammer", "ITEM_HAMMER_D": "Equip to enter build mode.",
	"ITEM_HOE": "Hoe", "ITEM_CULTIVATOR": "Cultivator", "ITEM_TORCH": "Torch",
	"ITEM_ANTLER_PICKAXE": "Antler Pickaxe", "ITEM_BRONZE_PICKAXE": "Bronze Pickaxe",
	"ITEM_IRON_PICKAXE": "Iron Pickaxe", "ITEM_BLACKMETAL_PICKAXE": "Black Metal Pickaxe",

	"ITEM_CLUB": "Club", "ITEM_STONE_AXE": "Stone Axe", "ITEM_FLINT_AXE": "Flint Axe",
	"ITEM_FLINT_SPEAR": "Flint Spear", "ITEM_FLINT_KNIFE": "Flint Knife",
	"ITEM_BRONZE_AXE": "Bronze Axe", "ITEM_BRONZE_SWORD": "Bronze Sword",
	"ITEM_BRONZE_MACE": "Bronze Mace", "ITEM_BRONZE_ATGEIR": "Bronze Atgeir",
	"ITEM_IRON_AXE": "Iron Axe", "ITEM_IRON_SWORD": "Iron Sword", "ITEM_IRON_MACE": "Iron Mace",
	"ITEM_IRON_ATGEIR": "Iron Atgeir", "ITEM_IRON_SPEAR": "Iron Spear",
	"ITEM_SILVER_SWORD": "Silver Sword", "ITEM_SILVER_MACE": "Silver Mace",
	"ITEM_FROSTNER": "Frostner", "ITEM_BLACKMETAL_SWORD": "Black Metal Sword",
	"ITEM_BLACKMETAL_AXE": "Black Metal Axe", "ITEM_BLACKMETAL_ATGEIR": "Black Metal Atgeir",
	"ITEM_MISTWALKER": "Mistwalker", "ITEM_FLAMETAL_GREATSWORD": "Flametal Greatsword",
	"ITEM_CRUDE_BOW": "Crude Bow", "ITEM_FINEWOOD_BOW": "Finewood Bow",
	"ITEM_HUNTSMAN_BOW": "Huntsman Bow", "ITEM_DRAUGR_FANG": "Draugr Fang",
	"ITEM_SPINE_SNAP": "Spine Snap",
	"ITEM_WOOD_ARROW": "Wood Arrow", "ITEM_FLINT_ARROW": "Flint Arrow",
	"ITEM_FIRE_ARROW": "Fire Arrow", "ITEM_BRONZE_ARROW": "Bronze Arrow",
	"ITEM_IRON_ARROW": "Iron Arrow", "ITEM_POISON_ARROW": "Poison Arrow",
	"ITEM_OBSIDIAN_ARROW": "Obsidian Arrow", "ITEM_FROST_ARROW": "Frost Arrow",
	"ITEM_NEEDLE_ARROW": "Needle Arrow",

	"ITEM_WOOD_SHIELD": "Wood Shield", "ITEM_BANDED_SHIELD": "Banded Shield",
	"ITEM_IRON_BUCKLER": "Iron Buckler", "ITEM_SILVER_SHIELD": "Silver Shield",
	"ITEM_BLACKMETAL_SHIELD": "Black Metal Shield", "ITEM_CARAPACE_BUCKLER": "Carapace Buckler",

	"ITEM_RAG_HOOD": "Rag Hood", "ITEM_RAG_TUNIC": "Rag Tunic",
	"ITEM_LEATHER_HELMET": "Leather Helmet", "ITEM_LEATHER_TUNIC": "Leather Tunic",
	"ITEM_LEATHER_PANTS": "Leather Pants", "ITEM_TROLL_HOOD": "Troll Hide Hood",
	"ITEM_TROLL_TUNIC": "Troll Hide Tunic", "ITEM_TROLL_PANTS": "Troll Hide Trousers",
	"ITEM_BRONZE_HELMET": "Bronze Helmet", "ITEM_BRONZE_CUIRASS": "Bronze Cuirass",
	"ITEM_BRONZE_GREAVES": "Bronze Greaves", "ITEM_IRON_HELMET": "Iron Helmet",
	"ITEM_IRON_SCALE_MAIL": "Iron Scale Mail", "ITEM_IRON_GREAVES": "Iron Greaves",
	"ITEM_WOLF_HEADDRESS": "Wolf Headdress", "ITEM_WOLF_ARMOR_CHEST": "Wolf Armor Chest",
	"ITEM_WOLF_ARMOR_LEGS": "Wolf Armor Legs", "ITEM_PADDED_HELMET": "Padded Helmet",
	"ITEM_PADDED_CUIRASS": "Padded Cuirass", "ITEM_PADDED_GREAVES": "Padded Greaves",
	"ITEM_CARAPACE_HELMET": "Carapace Helmet", "ITEM_CARAPACE_BREASTPLATE": "Carapace Breastplate",
	"ITEM_CARAPACE_LEGGUARDS": "Carapace Legguards",
	"ITEM_DEER_CAPE": "Deer Hide Cape", "ITEM_TROLL_CAPE": "Troll Hide Cape",
	"ITEM_WOLF_CAPE": "Wolf Fur Cape", "ITEM_LOX_CAPE": "Lox Cape",
	"ITEM_FEATHER_CAPE": "Feather Cape",

	"PIECE_CAMPFIRE": "Campfire", "PIECE_WORKBENCH": "Workbench", "PIECE_CHEST": "Chest",
	"PIECE_CHEST_LARGE": "Reinforced Chest", "PIECE_BED": "Bed", "PIECE_PORTAL": "Portal",
	"PIECE_SIGN": "Sign", "PIECE_RAFT": "Raft", "PIECE_KARVE": "Karve",
	"PIECE_LONGSHIP": "Longship", "PIECE_WOOD_FLOOR": "Wood Floor", "PIECE_WOOD_WALL": "Wood Wall",
	"PIECE_WOOD_WALL_HALF": "Wood Half Wall", "PIECE_WOOD_BEAM": "Wood Beam",
	"PIECE_WOOD_BEAM_26": "Wood Beam 26°", "PIECE_WOOD_POLE": "Wood Pole",
	"PIECE_WOOD_ROOF": "Wood Roof", "PIECE_WOOD_ROOF_TOP": "Roof Ridge",
	"PIECE_WOOD_DOOR": "Wood Door", "PIECE_WOOD_STAIR": "Wood Stair",
	"PIECE_WOOD_LADDER": "Ladder", "PIECE_WOOD_FENCE": "Wood Fence",
	"PIECE_STONE_FLOOR": "Stone Floor", "PIECE_STONE_WALL": "Stone Wall",
	"PIECE_STONE_PILLAR": "Stone Pillar", "PIECE_STONE_STAIR": "Stone Stair",
	"PIECE_HEARTH": "Hearth", "PIECE_TORCH_STAND": "Standing Torch", "PIECE_CHAIR": "Chair",
	"PIECE_TABLE": "Table", "PIECE_BANNER": "Banner", "PIECE_RUG_DEER": "Deer Rug",
	"PIECE_FORGE": "Forge", "PIECE_CAULDRON": "Cauldron", "PIECE_COOKING_STATION": "Cooking Station",
	"PIECE_SMELTER": "Smelter", "PIECE_CHARCOAL_KILN": "Charcoal Kiln",
	"PIECE_BLAST_FURNACE": "Blast Furnace", "PIECE_WINDMILL": "Windmill",
	"PIECE_SPINNING_WHEEL": "Spinning Wheel", "PIECE_ARTISAN_TABLE": "Artisan Table",
	"PIECE_STONECUTTER": "Stonecutter", "PIECE_FERMENTER": "Fermenter",
	"PIECE_WB_CHOPPING_BLOCK": "Chopping Block", "PIECE_WB_TANNING_RACK": "Tanning Rack",
	"PIECE_WB_ADZE": "Adze", "PIECE_WB_TOOL_SHELF": "Tool Shelf",
	"PIECE_FORGE_BELLOWS": "Forge Bellows", "PIECE_FORGE_ANVILS": "Anvils",
	"PIECE_FORGE_GRINDSTONE": "Grindstone", "PIECE_FORGE_TOOLRACK": "Forge Toolrack",
	"PIECE_PLANT_CARROT": "Plant Carrot", "PIECE_PLANT_TURNIP": "Plant Turnip",
	"PIECE_PLANT_ONION": "Plant Onion", "PIECE_PLANT_BARLEY": "Plant Barley",
	"PIECE_PLANT_FLAX": "Plant Flax", "PIECE_PLANT_BEECH": "Plant Beech",
	"PIECE_PLANT_PINE": "Plant Pine",

	"MOB_GREYLING": "Greyling", "MOB_NECK": "Neck", "MOB_BOAR": "Boar", "MOB_DEER": "Deer",
	"MOB_GREYDWARF": "Greydwarf", "MOB_GREYDWARF_BRUTE": "Greydwarf Brute",
	"MOB_GREYDWARF_SHAMAN": "Greydwarf Shaman", "MOB_TROLL": "Troll", "MOB_SKELETON": "Skeleton",
	"MOB_DRAUGR": "Draugr", "MOB_DRAUGR_ELITE": "Draugr Elite", "MOB_BLOB": "Blob",
	"MOB_OOZER": "Oozer", 
	"MOB_WOLF": "Wolf", "MOB_FENRING": "Fenring", "MOB_DRAKE": "Drake",
	"MOB_STONE_GOLEM": "Stone Golem", "MOB_FULING": "Fuling",
	"MOB_FULING_BERSERKER": "Fuling Berserker", 
	"MOB_DEATHSQUITO": "Deathsquito", "MOB_LOX": "Lox", "MOB_SEEKER": "Seeker",
	"MOB_SEEKER_SOLDIER": "Seeker Soldier", "MOB_GJALL": "Gjall", "MOB_TICK": "Tick",
	"MOB_CHARRED_WARRIOR": "Charred Warrior", "MOB_MORGEN": "Morgen", "MOB_VOLTURE": "Volture",

	"BOSS_EIKTHYR": "Eikthyr", "BOSS_ELDER": "The Elder", "BOSS_BONEMASS": "Bonemass",
	"BOSS_MODER": "Moder", "BOSS_YAGLUTH": "Yagluth", "BOSS_QUEEN": "The Queen",
	"BOSS_FADER": "Fader",

	"POWER_EIKTHYR": "Power of Eikthyr", "POWER_EIKTHYR_D": "Greatly reduces run and jump stamina cost.",
	"POWER_ELDER": "Power of the Elder", "POWER_ELDER_D": "Greatly reduces damage taken.",
	"POWER_BONEMASS": "Power of Bonemass", "POWER_BONEMASS_D": "Increases physical resistance.",
	"POWER_MODER": "Power of Moder", "POWER_MODER_D": "Constant tailwind, reduced fall damage.",
	"POWER_YAGLUTH": "Power of Yagluth", "POWER_YAGLUTH_D": "Increases movement speed.",
	"POWER_QUEEN": "Power of the Queen", "POWER_QUEEN_D": "Faster eitr regeneration.",
	"POWER_FADER": "Power of Fader", "POWER_FADER_D": "Greatly increases fire resistance.",

	"STATION_WORKBENCH": "Workbench", "STATION_FORGE": "Forge", "STATION_CAULDRON": "Cauldron",
	"STATION_ARTISAN_TABLE": "Artisan Table", "STATION_STONECUTTER": "Stonecutter",

	"WEATHER_CLEAR": "Clear", "WEATHER_CLOUDY": "Cloudy", "WEATHER_RAIN": "Rain",
	"WEATHER_STORM": "Storm", "WEATHER_SNOW": "Snowstorm", "WEATHER_MIST": "Thick Mist",
	"WEATHER_ASHFALL": "Ashfall",

	"STATUS_WET": "Wet", "STATUS_COLD": "Cold", "STATUS_FREEZING": "Freezing",
	"STATUS_POISON": "Poisoned", "STATUS_BURNING": "Burning", "STATUS_RESTED": "Rested",
	"STATUS_RES_FIRE": "Fire Resist", "STATUS_RES_FROST": "Frost Resist",
	"STATUS_RES_POISON": "Poison Resist",

	"SLOT_HEAD": "Head", "SLOT_CHEST": "Chest", "SLOT_LEGS": "Legs", "SLOT_CAPE": "Cape",
	"SLOT_RIGHT": "Weapon", "SLOT_LEFT": "Off-hand", "SLOT_AMMO": "Ammo",

	"UI_INVENTORY": "Inventory", "UI_CRAFTING": "Crafting", "UI_HANDCRAFT": "Hand Crafting",
	"UI_CHEST": "Chest", "UI_TOMBSTONE": "Tombstone", "UI_MAP": "Map", "UI_SKILLS": "Skills",
	"UI_STATS": "Records", "UI_POWERS": "Forsaken Powers", "UI_PAUSED": "Paused",
	"UI_RESUME": "Resume", "UI_SAVE": "Save (F5)", "UI_LOAD": "Load (F9)",
	"UI_QUIT": "Save & Quit", "UI_YOU_DIED": "You have fallen",
	"UI_DEATH_DESC": "Your belongings rest in a tombstone where you fell. All skills lowered by 5%.",
	"UI_RESPAWN": "Respawn", "UI_CRAFT": "Craft", "UI_UPGRADE": "Upgrade",
	"UI_TAB_CRAFT": "Craft", "UI_TAB_UPGRADE": "Upgrade",
	"UI_NO_RECIPES": "Nothing can be made here.", "UI_NO_UPGRADES": "Nothing to upgrade.",
	"UI_SELECT_RECIPE": "Select an entry on the left.",
	"UI_DAY": "Day %d", "UI_WEIGHT": "Weight %d / %d", "UI_ARMOR": "Armor %d",
	"UI_WEIGHT_ONE": "Weight %.1f", "UI_NO_TELEPORT": "Cannot be teleported",
	"UI_QUALITY": "Quality %d / %d",
	"UI_ATTACK_SPEED": "Attack speed: %.2f", "UI_STAMINA_COST": "Stamina: %d",
	"UI_BLOCK_POWER": "Block power: %d", "UI_PARRY": "Parry bonus: %.1fx",
	"UI_ARMOR_VALUE": "Armor: %d", "UI_FOOD_HP": "Max health +%d",
	"UI_FOOD_SP": "Max stamina +%d", "UI_FOOD_TIME": "Duration %d min",
	"UI_FOOD_REGEN": "Health regen %.1f", "UI_TOOL_TIER": "Mining tier %d",
	"UI_CHOP_TIER": "Chopping tier %d",
	"UI_INV_HINT": "LMB pick/place · RMB equip/use · Shift+LMB move to chest",
	"UI_CAT_MISC": "Misc", "UI_CAT_WOOD": "Wood", "UI_CAT_STONE": "Stone",
	"UI_CAT_FURNITURE": "Furniture", "UI_CAT_STATIONS": "Stations", "UI_CAT_UPGRADES": "Upgrades",
	"UI_CAT_FARMING": "Farming",
	"UI_BUILD_HINT": "Selected: %s",
	"UI_BUILD_KEYS": "LMB place · RMB remove · R rotate",
	"UI_NEEDS_WORKBENCH": "Requires a workbench nearby",
	"UI_NEEDS_FUEL": "Needs coal", "UI_BURNT": "Burnt", "UI_COOKED": "Done",
	"UI_NO_POWERS": "No powers yet. Defeat a boss.",
	"UI_POWER_HINT": "Press F to activate (5 min cooldown)",
	"UI_CONTROLS": "WASD move · Shift sprint · Space jump · Ctrl crouch · Alt dodge\nE interact · Tab inventory · M map · K skills · P powers · Hammer to build\nLMB attack · RMB block · 1-8 hotbar",
	# ── Multiplayer ──
	"UI_MULTIPLAYER": "Multiplayer", "UI_HOST": "Host game", "UI_JOIN": "Join",
	"UI_IP": "Address", "UI_PORT": "Port", "UI_NICKNAME": "Name",
	"UI_CHAT": "Chat", "UI_CHAT_HINT": "Enter to send, Esc to close",
	"UI_PLAYERS_ONLINE": "Online",
	"NET_OFFLINE": "Singleplayer", "NET_HOSTING": "Host", "NET_CLIENT": "Client",
	"NET_PLAYERS": "%d online",
	"MSG_NET_HOSTING": "Hosting on port %d.",
	"MSG_NET_HOST_FAIL": "Could not host (error %d).",
	"MSG_NET_CONNECTING": "Connecting to %s...",
	"MSG_NET_CONNECTED": "Connected to server.",
	"MSG_NET_JOIN_FAIL": "Connection failed.",
	"MSG_NET_SERVER_GONE": "Lost connection to the server.",
	"MSG_NET_JOINED_PEER": "%s joined.",
	"MSG_NET_LEFT_PEER": "%s left.",
	# ── 확장 콘텐츠 (item names) ──
	"ITEM_BIRCH_SEEDS": "Birch Seeds", "ITEM_FIR_CONE": "Fir Cone", "ITEM_RASPBERRY_SEEDS": "Raspberry Seeds",
	"ITEM_VINE_SEEDS": "Vine Seeds", "ITEM_JUTE_RED": "Red Jute", "ITEM_JUTE_BLUE": "Blue Jute",
	"ITEM_LEATHER_BELT": "Leather Belt", "ITEM_WISP": "Wisp", "ITEM_ROOT": "Root",
	"ITEM_IRON_INGOT_SCRAP": "Iron Billet", "ITEM_TAR": "Tar", "ITEM_BAT_WING": "Bat Wing",
	"ITEM_SERPENT_SCALE": "Serpent Scale", "ITEM_SERPENT_TROPHY_SCALE": "Great Serpent Scale", "ITEM_BONE_MASS": "Bone Mass",
	"ITEM_CHITIN": "Chitin", "ITEM_MARBLE": "Marble", "ITEM_GRAUSTEN": "Grausten",
	"ITEM_CERAMIC_PLATE": "Ceramic Plate", "ITEM_PROUSTITE": "Proustite", "ITEM_RUBY": "Ruby",
	"ITEM_AMBER": "Amber", "ITEM_AMBER_PEARL": "Amber Pearl", "ITEM_COINS": "Coins",
	"ITEM_SILVER_NECKLACE": "Silver Necklace", "ITEM_PERCH": "Perch", "ITEM_PIKE": "Pike",
	"ITEM_TUNA": "Tuna", "ITEM_TROLLFISH": "Trollfish", "ITEM_MAGMAFISH": "Magmafish",
	"ITEM_NORTHERN_SALMON": "Northern Salmon", "ITEM_COOKED_PERCH": "Cooked Perch", "ITEM_COOKED_PIKE": "Cooked Pike",
	"ITEM_COOKED_TUNA": "Cooked Tuna", "ITEM_COOKED_MAGMAFISH": "Cooked Magmafish", "ITEM_GRILLED_NECK_TAIL": "Grilled Neck Tail",
	"ITEM_HONEY_GLAZED_CHICKEN": "Honey Glazed Chicken", "ITEM_BOAR_JERKY": "Boar Jerky", "ITEM_DEER_STEW": "Deer Stew",
	"ITEM_MINCED_MEAT_SAUCE": "Minced Meat Sauce", "ITEM_BREAD_AND_HONEY": "Bread and Honey", "ITEM_MUSHROOM_STEW": "Mushroom Stew",
	"ITEM_BERRY_PIE": "Berry Pie", "ITEM_WOLF_SKEWER": "Wolf Skewer", "ITEM_SERPENT_STEW": "Serpent Stew",
	"ITEM_FISH_AND_BREAD": "Fish and Bread", "ITEM_BLOOD_SAUSAGE": "Blood Sausage", "ITEM_MISTHARE_SUPREME": "Misthare Supreme",
	"ITEM_YGGDRASIL_PORRIDGE": "Yggdrasil Porridge", "ITEM_SEEKER_ASPIC": "Seeker Aspic", "ITEM_MEAD_TASTY": "Tasty Mead",
	"ITEM_MEAD_MEDIUM_HEALTH": "Medium Healing Mead", "ITEM_MEAD_MINOR_EITR": "Minor Eitr Mead", "ITEM_MEAD_LINGERING_STAMINA": "Lingering Stamina Mead",
	"ITEM_MEAD_BZERKER": "Bzerker Mead", "ITEM_WOOD_CLUB": "Wooden Club", "ITEM_BONE_KNIFE": "Bone Knife",
	"ITEM_BRONZE_KNIFE": "Bronze Knife", "ITEM_IRON_KNIFE": "Iron Knife", "ITEM_SILVER_KNIFE": "Silver Knife",
	"ITEM_BLACKMETAL_KNIFE": "Blackmetal Knife", "ITEM_BRONZE_SPEAR": "Bronze Spear", "ITEM_ANCIENT_BARK_SPEAR": "Ancient Bark Spear",
	"ITEM_BLACKMETAL_SPEAR": "Blackmetal Spear", "ITEM_BATTLEAXE_CRYSTAL": "Crystal Battleaxe", "ITEM_PORCUPINE": "Porcupine",
	"ITEM_DAGGER_DYRNWYN": "Dyrnwyn", "ITEM_STAGBREAKER": "Stagbreaker", "ITEM_CRYSTAL_BATTLEAXE": "Crystal Greataxe",
	"ITEM_BONE_ARROW": "Bone Arrow", "ITEM_SILVER_ARROW": "Silver Arrow", "ITEM_CARAPACE_ARROW": "Carapace Arrow",
	"ITEM_FLAMETAL_ARROW": "Flametal Arrow", "ITEM_BRONZE_BUCKLER": "Bronze Buckler", "ITEM_BONE_TOWER_SHIELD": "Bone Tower Shield",
	"ITEM_SERPENT_SCALE_SHIELD": "Serpent Scale Shield", "ITEM_FLAMETAL_SHIELD": "Flametal Shield", "ITEM_ROOT_MASK": "Root Mask",
	"ITEM_ROOT_HARNESK": "Root Harnesk", "ITEM_ROOT_LEGGINGS": "Root Leggings", "ITEM_LINEN_HOOD": "Linen Hood",
	"ITEM_FENRIS_HOOD": "Fenris Hood", "ITEM_FENRIS_COAT": "Fenris Coat", "ITEM_FENRIS_LEGGINGS": "Fenris Leggings",
	"ITEM_EITR_WEAVE_HOOD": "Eitr-weave Hood", "ITEM_EITR_WEAVE_ROBE": "Eitr-weave Robe", "ITEM_EITR_WEAVE_TROUSERS": "Eitr-weave Trousers",
	"ITEM_FLAMETAL_HELMET": "Flametal Helmet", "ITEM_FLAMETAL_CUIRASS": "Flametal Cuirass", "ITEM_FLAMETAL_GREAVES": "Flametal Greaves",
	"ITEM_LINEN_CAPE": "Linen Cape", "ITEM_ASH_CAPE": "Ash Cape", "ITEM_TROPHY_SERPENT": "Serpent Trophy",
	"ITEM_TROPHY_LEECH": "Leech Trophy", "ITEM_TROPHY_SURTLING": "Surtling Trophy", "ITEM_TROPHY_BAT": "Bat Trophy",
	"ITEM_TROPHY_HARE": "Misthare Trophy", "ITEM_TROPHY_GJALL": "Gjall Trophy", "ITEM_TROPHY_TICK": "Tick Trophy",
	"ITEM_TROPHY_DVERGR": "Dvergr Trophy", "ITEM_TROPHY_ASKSVIN": "Asksvin Trophy", "ITEM_TROPHY_CHARRED": "Charred Trophy",
	"ITEM_TROPHY_FADER": "Fader Trophy",
	# ── 확장 생물 ──
	"MOB_CHICKEN": "Chicken", "MOB_BAT": "Bat", 
	"MOB_SERPENT": "Sea Serpent", "MOB_HARE": "Misthare",
	"MOB_DVERGR": "Dvergr", "MOB_ASKSVIN": "Asksvin", "MOB_CHARRED_ARCHER": "Charred Archer",
	"MOB_SKELETON_ARCHER": "Skeleton Archer", 
	"MOB_SURTLING": "Surtling", "MOB_LEECH": "Leech", "MOB_WRAITH": "Wraith",
	"MOB_FULING_SHAMAN": "Fuling Shaman",
	# ── Runestone lore ──
	"UI_RUNESTONE": "Runestone", "PROMPT_READ_RUNESTONE": "[E] Read runestone",
	"LORE_1": "\"Odin sent us here. The tenth world, land of the unjudged.\"",
	"LORE_2": "\"The antlered one rules the forest. When you hear the hooves, raise your bow.\"",
	"LORE_3": "\"We mined iron from the marsh. Half of us never came back for it.\"",
	"LORE_4": "\"Nothing grows on the mountain. Only cold, and what endures cold.\"",
	"LORE_5": "\"Grass on the plains stands taller than a man, and things with three eyes hide in it.\"",
	"LORE_6": "\"In the mist, do not trust sound. The mist imitates it.\"",
	"LORE_7": "\"In the land of fire even stone burns. All we left behind was ash.\"",
	"LORE_8": "\"Offer at the five altars and the gate opens - whether that is a blessing, I cannot say.\"",
	"LORE_9": "\"I have died thirty-seven times and returned thirty-seven times. That is the punishment.\"",
	"LORE_10": "\"Valhalla lies beyond this. Dying here will not take you there.\"",
	"UI_TITLE": "VALHALLA",
	"UI_SUBTITLE": "A Norse survival homage to Valheim",
	"UI_NEW_GAME": "New World", "UI_CONTINUE": "Continue", "UI_SEED": "Seed",
	"UI_RANDOM_SEED": "Random", "UI_START": "Begin", "UI_LOADING": "Forging the world...",
	"UI_EXIT": "Exit",

	"PROMPT_PICK": "Pick %s", "PROMPT_OPEN": "Open %s", "PROMPT_TAKE_ALL": "Take all",
	"PROMPT_DOOR": "Open/close door", "PROMPT_SLEEP": "Sleep", "PROMPT_SIT": "Sit",
	"PROMPT_COOK": "Cook", "PROMPT_INSERT": "Insert", "PROMPT_CRAFT": "Craft",
	"PROMPT_HARVEST": "Harvest", "PROMPT_PORTAL": "Use portal",
	"PROMPT_OFFER": "Offer to %s (%s)",
	"PROMPT_EMBARK": "Board the %s", "PROMPT_DISEMBARK": "Disembark",

	"MSG_YOU_DIED": "You have fallen...", "MSG_TOO_WEAK": "Tool too weak",
	"MSG_BLOCKED": "Blocked!", "MSG_PARRY": "Parry!", "MSG_STAGGERED": "Staggered!",
	"MSG_SKILL_UP": "%s reached level %d", "MSG_NEW_DAY": "Day %d dawns",
	"MSG_CRAFTED": "Crafted %s", "MSG_UPGRADED": "Upgraded %s to ★%d",
	"MSG_NOT_ENOUGH": "Not enough materials", "MSG_INVENTORY_FULL": "Inventory full",
	"MSG_ATE": "Ate %s", "MSG_DRANK": "Drank %s", "MSG_TOO_FULL": "You are too full",
	"MSG_SLEPT": "You slept well.", "MSG_CANT_SLEEP": "You can only sleep at night",
	"MSG_STATION_FULL": "No room left", "MSG_NOTHING_TO_COOK": "Nothing to cook",
	"MSG_NOTHING_TO_SMELT": "Nothing to smelt", "MSG_NO_PORTAL": "No connected portal",
	"MSG_PORTAL_BLOCKED": "%s cannot pass through a portal",
	"MSG_NEED_OFFERING": "Not enough offerings",
	"MSG_BOSS_SUMMONED": "%s awakens!", "MSG_BOSS_DEFEATED": "%s defeated! A new power is yours.",
	"MSG_BOSS_ENRAGED": "%s is enraged!", "MSG_BOSS_SUMMONS": "The boss calls for aid!",
	"MSG_POWER_ACTIVATED": "%s activated!", "MSG_RAID": "Something is approaching...",
	"MSG_SAVED": "Saved", "MSG_LOADED": "Loaded", "MSG_NO_SAVE": "No save file",
	"MSG_SAVE_FAILED": "Save failed", "MSG_SAVE_CORRUPT": "Save file corrupted",
	"MSG_LANG_CHANGED": "Language changed",
	"MSG_WELCOME": "The raven whispers: light a fire, raise a roof, and endure.",
	"MSG_HOE_LEVEL": "Hoe: Level", "MSG_HOE_RAISE": "Hoe: Raise", "MSG_HOE_DIG": "Hoe: Dig",
	"MSG_NO_BAIT": "No bait", "MSG_FISH_BITE": "A bite! Left-click",
	"MSG_FISH_HOOKED": "Hooked! Hold left-click to reel",
	"MSG_FISH_ESCAPED": "It got away", "MSG_FISH_LOST": "Out of stamina — the line snapped",
	"MSG_FISH_TOO_SHALLOW": "Too shallow",
	"MSG_NO_EITR_FOOD": "No eitr — eat magic food first",
	"MSG_NOT_ENOUGH_EITR": "Not enough eitr",
	"MSG_SHIELD_UP": "A magic ward surrounds you", "MSG_SUMMONED": "Skeletons rise",
	"MSG_TAMED": "%s is tamed", "MSG_TAMING": "%s is warming to you",
	"MSG_BABY_BORN": "A %s calf is born",
	"ITEM_FISHING_ROD": "Fishing Rod", "ITEM_FISHING_BAIT": "Fishing Bait",
	"ITEM_LEECH_FISH": "Leech Fish",
	"ITEM_STAFF_FIRE": "Staff of Embers", "ITEM_STAFF_FROST": "Staff of Frost",
	"ITEM_STAFF_SHIELD": "Staff of Protection", "ITEM_STAFF_SKELETON": "Skeleton Staff",
	"ITEM_SAP_STEW": "Sap Stew", "ITEM_MUSHROOM_OMELETTE": "Mushroom Omelette",
	"STATUS_MAGIC_SHIELD": "Magic Ward",
	"UI_EITR": "Eitr",
	"DUNGEON_CRYPT": "Burial Chamber", "DUNGEON_SUNKEN": "Sunken Crypt",
	"DUNGEON_CAVE": "Frost Cave", "UI_DUNGEON_EXIT": "Exit",
	"PROMPT_ENTER_DUNGEON": "Enter the %s", "PROMPT_EXIT_DUNGEON": "Leave",
	"MSG_ENTER_DUNGEON": "Damp air and the smell of old stone.",
	"MSG_EXIT_DUNGEON": "You return beneath the open sky.",

	"ALTAR_DEFEATED": "%s — defeated",

	"STAT_KILLS": "Kills", "STAT_DEATHS": "Deaths", "STAT_CRAFTED": "Crafted",
	"STAT_BUILT": "Built", "STAT_TREES": "Trees felled", "STAT_DISTANCE": "Distance",
}
